# ==========================================================
# Data source CONFIGURATION
# ==========================================================
data_source:
  - type: csv
    input_path: data/raw/Telco Customer Churn.csv
    output_path: data/processed/processed_data.csv

  - type: db
    db_name: postgres
    user_name: postgres
    password: root
    host: localhost
    port: 5432
    query: SELECT * FROM telco_customer_churn
    table: processed_telco_customer_churn

  - type: json
    input_path: data/raw/telco_customer_churn.json
    output_path: data/processed/processed_telco_customer_churn.json

# ==========================================================
# Output CONFIGURATION 
# ==========================================================
dropped_records: data/dropped/dropped_records.csv
# output:
#   - type: csv
#     path: data/processed/processed_data.csv

#   - type: db
#     database:
#       db_name: postgres
#       user_name: postgres
#       password: root
#       host: localhost
#       port: 5432
#       table: processed_telco_customer_churn

#   - type: json
#     path: data/processed/processed_telco_customer_churn.json
# ==========================================================
# Handle missing value CONFIGURATION
# ==========================================================
changes:
  - type: StandardizeColumns

  - type: ToNumeric
    column: [tenure, monthlycharges, totalcharges]

  - type: HandleIntegerMissingValues
    column: totalcharges

  - type: DropNull

  - type: DropColumn
    column: customerid

  - type: Encoding
# ==========================================================
# Validation CONFIGURATION
# ==========================================================
validation:
  threshold: 0.1
  missing_values:
    replace_with_nan: [" ", "", "NA", "null"]
  rules:
    - column: tenure
      condition: "< 0"

    - column: monthlycharges
      condition: "<= 0"

    - column: totalcharges
      condition: "<= 0"

    - column: churn
      condition: "map:Yes=1,No=0"

# ==========================================================
# Logging CONFIGURATION
# ==========================================================
logging:
  log_file: log/pipeline.log